### ISSUE TITLE
Jekyll syntax highlighting 관련

### ISSUE THREAD

**Issue by mooneegee** [StonzeTeam/StonzeTeam.github.io#1]
코드는 정상적으로 보입니다.

바탕 색이 누렇게 떠보이는게 이거 커스터마이징 가능하면 깔끔한 블랙으로 수정해주십시오.

**Comment by mastrayer** [comment]
https://github.com/StonzeTeam/StonzeTeam.github.io/commit/1bd16034a5f40ca98049d91e29e994c41168e8c3
